### PR TITLE
Mutating nested properties validations loose validations

### PR DESCRIPTION
**Pull request by basz**
This adds a failing test for nested properties and validations. Initially, the validations run fine, but after changes to the input the validations seem to get lost.

I have posted an initial issue to ember-changeset, however I suspect it might be an issue in ember-bootstrap or 
ember-bootstrap-changeset-validations, as nested properties and validtions seem to be correctly working in ember-changeset.

see https://github.com/poteto/ember-changeset/issues/521

Running `ember server` inside the tests/dummy app visually shows the problem...

### CODE REVIEW

**Comment by jelhan** [comment]
I'm wondering if having a path as `property` argument is supported by `<BsForm::Element>`. The documentation only talks about property name: https://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_property

Is using a path mentioned somewhere else in the documentation? Or is there a test coverage for it in Ember Bootstrap? If not we should discuss first at Ember Bootstrap level if we want to support it.

**Comment by basz** [comment]
Fair enough... But,... if it is not, it should be... documented..., took me forever to figure out...

**Comment by jelhan** [comment]
> Fair enough... But,... if it is not, it should be... documented..., took me forever to figure out...

It was an open question. I'm not sure if it's supported. And I'm not sure if it should be supported. But I agree that we should have a clear answer to that question. Therefore to would be awesome if you can research that topic.

**Comment by basz** [comment]
It's more that I naively expected it to work, depended on to and used to work. IMO it really makes sense as the structure of data and form representation can work together.

I do recognize managing nested data with validated changesets and form UI is complicated. Since tracked properties have been introduced many refactorings have been done (mainly to ember-changeset) which have partially broken functionality at times. I hoped that we almost found all remaining bugs and both libraries would enter a stable state again.

So, considering the hours I have poured into locating these issues and the cost of refactoring my application I would love to support such a feature if it is at all possible. Then again; I do need help as I am stuck at further pinning down the problem as I do not understand why a validation would get lost.

But, when it is decided to not be supported, I would accept that as a fact too. (I would cry though)

@lolmaus @nickschot @simonihmig my I ask your opinions?

greets, Bas

**Comment by jelhan** [comment]
I opened this issue in Ember Bootstrap repository: https://github.com/kaliber5/ember-bootstrap/issues/1173 I think that's the correct place to discuss it as the decision would not only affect this plugin library. The Ember Bootstrap repository has more visibility.

**Pull request closed without merging**
